version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: bitrix-web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitrix-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    container_name: bitrix-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: example_password
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bitrix-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: bitrix
      PMA_PASSWORD: example_password
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    restart: always  

  # memcached:
  #   image: memcached:latest
  #   container_name: bitrix-memcached
  #   ports:
  #     - "11211:11211"
  #   restart: always  

volumes:
  mysql_data:
